// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.At":       schema_pkg_apis_cnat_v1alpha1_At(ref),
		"github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtSpec":   schema_pkg_apis_cnat_v1alpha1_AtSpec(ref),
		"github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtStatus": schema_pkg_apis_cnat_v1alpha1_AtStatus(ref),
	}
}

func schema_pkg_apis_cnat_v1alpha1_At(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "At is the Schema for the ats API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtSpec", "github.com/programming-kubernetes/cnat/cnat-operator/pkg/apis/cnat/v1alpha1.AtStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_cnat_v1alpha1_AtSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AtSpec defines the desired state of At",
				Properties: map[string]spec.Schema{
					"schedule": {
						SchemaProps: spec.SchemaProps{
							Description: "Schedule is the desired time the command is supposed to be executed. Note: the format used here is UTC time https://www.utctime.net",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"command": {
						SchemaProps: spec.SchemaProps{
							Description: "Command is the desired command (executed in a Bash shell) to be executed.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_cnat_v1alpha1_AtStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "AtStatus defines the observed state of At",
				Properties: map[string]spec.Schema{
					"phase": {
						SchemaProps: spec.SchemaProps{
							Description: "Phase represents the state of the schedule: until the command is executed it is PENDING, afterwards it is DONE.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}
